apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: manager-config

resources:
- deployment.yaml

images:
- name: controller
  newName: ghcr.io/mmz-srf/akamai-operator
  newTag: v0.3.1
